package com.iotauth.iot_auth.domain.enums;

public enum EventType {
    DEVICE_PRE_REGISTERED,
    FIRST_CONTACT_RECEIVED,
    FIRST_CONTACT_REJECTED,
    CHALLENGE_ISSUED,
    CHALLENGE_VALIDATED,
    CHALLENGE_FAILED,
    DEVICE_ACTIVATED,
    VC_ISSUED,
    JWT_ISSUED,
    AUTH_CACHE_HIT,
    AUTH_CACHE_MISS,
    VP_CHALLENGE_ISSUED,
    VP_VALIDATED,
    VP_REJECTED,
    JWT_RENEWED,
    DEVICE_SUSPENDED,
    DEVICE_REACTIVATED,
    DEVICE_REVOKED,
    REVOKED_DEVICE_ACCESS_ATTEMPT,
    PERMISSION_VIOLATION,
    ALGORAND_PUBLICATION_FAILED,
    ALGORAND_PUBLICATION_CONFIRMED
}
