spring.application.name=iot-auth
spring.docker.compose.enabled=false

# PostgreSQL Database for Development
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/iot_auth_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:malick}
spring.datasource.password=${DB_PASSWORD:1234}


# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis (Embedded or Local)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Admin Key Configuration (Base64 encoded Ed25519 private key)
# If not set, a random key will be generated
iot.auth.admin-private-key-base64=

# JWT Configuration
iot.auth.jwt-ttl-seconds=3600
iot.auth.nonce-ttl-seconds=60
iot.auth.redis-ttl-seconds=300
iot.auth.vc-validity-days=365

iot.auth.failure-ttl-seconds-challenge=600
iot.auth.failure-threshold-challenge=5

iot.auth.failure-ttl-seconds-vp=300
iot.auth.failure-threshold-vp=3

iot.auth.failure-ttl-seconds-perm=3600
iot.auth.failure-threshold-perm=1
iot.auth.inactivity-monitor.enabled=true
iot.auth.inactivity-monitor.timeout-seconds=90
iot.auth.inactivity-monitor.initial-delay-ms=30000
iot.auth.inactivity-monitor.scan-interval-ms=30000

# Algorand LocalNet / AlgoKit Sandbox
iot.auth.algorand.algod-address=http://localhost
iot.auth.algorand.algod-port=4001
iot.auth.algorand.algod-token=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
iot.auth.algorand.indexer-address=http://localhost
iot.auth.algorand.indexer-port=8980
iot.auth.algorand.indexer-token=
iot.auth.algorand.network=localnet

# Server Configuration
server.port=8083

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always



iot.auth.gateway.shared-secret=${IOT_AUTH_GATEWAY_SHARED_SECRET:dev-gateway-secret}
iot.auth.admin.jwt-secret=${IOT_AUTH_ADMIN_JWT_SECRET:ZGV2LWFkbWluLWp3dC1zZWNyZXQtZGV2LWFkbWluLWp3dC1zZWNyZXQtMzJi}

iot.auth.algorand.app-id=${ALGORAND_APP_ID:1010}
iot.auth.algorand.deployer-mnemonic=${ALGORAND_DEPLOYER_MNEMONIC:}
